### PR TITLE
Fix multiline diagnostic snippet

### LINKED ISSUE #310: [Bug]: Multiline errors only show the first line in error messages
### Description

$subject

### Steps to Reproduce

_No response_

### Affected Version(s)

_No response_

### OS, DB, other environment details and versions

_No response_

### Related area

Compilation

### Related issue(s) (optional)

_No response_

### Suggested label(s) (optional)

_No response_

### Suggested assignee(s) (optional)

_No response_

### PR DESCRIPTION
**Pull request by snelusha**
## Purpose
Resolves #310
Depends on #264 

## Summary by CodeRabbit

* **Bug Fixes**
  * Diagnostics now render multi-line source context for ranged errors with per-line numbers and aligned pointers.
  * Highlighting is clamped to line bounds, trims surrounding whitespace, guarantees a minimal caret when needed, and skips invalid empty spans.

* **Tests**
  * Numerous diagnostic expectation fixtures updated to reflect expanded per-line spans (including inner statements and closing braces).

### CODE REVIEW

**Review by heshanpadmasiri — DISMISSED** [review]
LGTM

**Review by heshanpadmasiri — DISMISSED** [review]
LGTM

File: corpus/diagnostic_printer.go [hunk 1]
```diff
@@ -102,17 +105,61 @@ func printSourceSnippet(w io.Writer, loc diagnosticLocation, fsys fs.FS) {
...
+			break
+		}
+	}
+	lastNonWS := len(lineContent)
+	hasNonWS := firstNonWS != -1
+	if hasNonWS {
+		for lastNonWS > firstNonWS && (lineContent[lastNonWS-1] == ' ' || lineContent[lastNonWS-1] == '\t') {
+			lastNonWS--
+		}
+	}
```
Comment (warunalakshitha) [inline corpus/diagnostic_printer.go:154]: this whole logic is duplicated in utils.go too. we need to think how we can reuse that. may be fix in another pr. if not in the future utils changes might not sync to diagnostic_printer

Comment (snelusha) [reply corpus/diagnostic_printer.go:154]: Yes we agreed to this. But we should reuse this somehow.

**Review by warunalakshitha — APPROVED** [review]
