### PR TITLE
Fix variable initialization for decimal literals

### LINKED ISSUE #204: Variable initialization fails for decimal literals
The following two cases with decimal are not compiling:

```ballerina
 decimal d = 100d; // Semantic error: incompatible type: expected ((DECIMAL), ()), got ((), (INT)
 decimal d = 123; // panic: Syntax error: invalid decimal literal: 100d
```

Both cases result in syntax errors.

### PR DESCRIPTION
**Pull request by heshanpadmasiri**
## Purpose
Resolves #204

## Automation tests
 - Unit tests 
   > Code coverage information
 - Integration tests
   > Details about the test cases and coverage

## Security checks
 - Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes/no
 - Ran FindSecurityBugs plugin and verified report? yes/no
 - Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes/no

 

## Summary by CodeRabbit

* **New Examples**
  * Added a small example program demonstrating numeric literals, mixed-type arrays, casting, and printed output.

* **Improvements**
  * Enhanced implicit widening of numeric literals to allow integer → float/decimal conversions based on context.
  * Improved handling of floating-point type suffixes when parsing numeric literals.

### CODE REVIEW

File: semantics/semantic_analyzer.go [hunk 1]
```diff
@@ -467,13 +468,55 @@ func validateResolvedType[A analyzer](a A, expr ast.BLangExpression, expectedTyp
 	return true
 }
 
+func maybeWidenNumericLiteral[A analyzer](a A, expr *ast.BLangLiteral, expectedType semtypes.SemType) {
```
Comment (warunalakshitha) [inline semantics/semantic_analyzer.go]:
```suggestion
func widenNumericLiteral[A analyzer](a A, expr *ast.BLangLiteral, expectedType semtypes.SemType) {
```

File: semantics/type_resolver.go [hunk 2]
```diff
@@ -300,6 +300,18 @@ func (t *TypeResolver) resolveLiteral(n *ast.BLangLiteral) {
 	updateSymbolType(t.ctx, n, ty)
 }
 
+// stripFloatingPointTypeSuffix removes the f/F/d/D type suffix from a floating point literal string
+func stripFloatingPointTypeSuffix(s string) string {
+	if len(s) == 0 {
+		return s
```
Comment (warunalakshitha) [inline semantics/type_resolver.go]: Can length be 0. what happen length is 1 and d

Comment (heshanpadmasiri) [reply semantics/type_resolver.go]: for length 1 and d it will be parsed as variable reference. Removed check for length

File: semantics/semantic_analyzer.go (hunk 1 above)
Comment (heshanpadmasiri) [reply semantics/semantic_analyzer.go]: Fixed

**Review by warunalakshitha — APPROVED** [review]
LGTM
