### PR TITLE
Fix diagnostics printing and migrate integration tests to txtar

### LINKED ISSUE #46: Implement error message support
After #45 we should have enough errors to produce error messages (`-e.bal` tests). We need to think how to show these errors to the user

### PR DESCRIPTION
**Pull request by snelusha**
## Purpose
$subject

Resolves #46 

## Summary by CodeRabbit

* **Bug Fixes**
  * Diagnostics are now location-aware and accumulate instead of causing abrupt failures.

* **New Features**
  * Terminal diagnostics printer with colorized headers, file snippets, and caret highlighting.

* **Improvements**
  * Clearer, more precise diagnostic formatting with source-context display.
  * Compiler initialization moved to a stable environment-based flow.

* **Tests**
  * Test harnesses updated for flag-driven runs and parallel discovery.

### CODE REVIEW

File: cli/cmd/run.go [hunk 1]
```diff
@@ -187,8 +194,15 @@ func runBallerina(cmd *cobra.Command, args []string) error {
 	// Run semantic analysis after type resolution
 	semanticAnalyzer := semantics.NewSemanticAnalyzer(cx)
 	semanticAnalyzer.Analyze(pkg)
-	// Run CFG analyses (reachability and explicit return) concurrently
+
+	// Run CFG analyses (reachability and explicit return)
```
Comment (heshanpadmasiri) [inline cli/cmd/run.go]: I hope this is still concurrent

File: context/context.go [hunk 2]
```diff
@@ -134,6 +139,122 @@ func (this *CompilerContext) InternalError(message string, pos diagnostics.Locat
...
+}
+
+func (this *CompilerContext) PrintDiagnostics(w io.Writer) {
+	if this.HasDiagnostics() {
+		fmt.Fprintln(w, "\nCompilation failed with the following errors:")
+		for _, diagnostic := range this.diagnostics {
+			this.printDiagnostic(w, diagnostic)
+		}
+	}
+}
```
Comment (heshanpadmasiri) [inline context/context.go]: I don't think this should be in compiler context. If needs be a separate function is okay but I don't like having it in context.go. These details are irrelevant for  front end

File: corpus/integration/subset1/01-boolean/not1-e.bal.txtar [hunk 3]
```diff
@@ -0,0 +1,3 @@
+-- stdout --
+-- stderr --
+panic: interface conversion: interface is nil, not semtypes.ComplexSemType
```
Comment (heshanpadmasiri) [inline corpus/integration/subset1/01-boolean/not1-e.bal.txtar]: I think this is a bug, In main this gives a proper syntax error. Also for -e test cases they should only give semantic or syntax errors

File: corpus/integration/subset1/01-boolean/not3-e.bal.txtar [hunk 4]
```diff
@@ -0,0 +1,22 @@
+-- stdout --
+-- stderr --
+
+Compilation failed with the following errors:
+[1m[31merror[SEMANTIC_ERROR][0m: [1mexpect boolean type for ![0m
```
Comment (heshanpadmasiri) [inline corpus/integration/subset1/01-boolean/not3-e.bal.txtar]: I think we discussed these control characters should only be there when sending to terminals that support them?

File: corpus/integration/subset1/01-function/assign7-e.bal.txtar [hunk 5]
```diff
@@ -0,0 +1,3 @@
+-- stdout --
+-- stderr --
+panic: Internal error: variable reference has no symbol at &{../corpus/bal/subset1/01-function/assign7-e.bal %!s(int=19) %!s(int=19) %!s(int=4) %!s(int=5) %!s(int=703) %!s(int=1)}
```
Comment (heshanpadmasiri) [inline corpus/integration/subset1/01-function/assign7-e.bal.txtar]: Check this as well. I have no idea why you are getting these errors but they are not in the main. Also if this is the position "%!s(int=19) %!s(int=19) %!s(int=4) %!s(int=5) %!s(int=703) %!s(int=1)" I think we need to give a human redable position instead

File: corpus/integration_test.go [hunk 6]
```diff
@@ -88,11 +86,14 @@ type testResult struct {
...
 const (
-	skipReasonErrorFile skipReason = iota // -e.bal files
-	skipReasonSkipList                    // files in skipTestsMap
+	skipReasonSkipList skipReason = iota // files in skipTestsMap
 )
 
 func TestIntegrationSuite(t *testing.T) {
+	if !flag.Parsed() {
+		flag.Parse()
+	}
```
Comment (heshanpadmasiri) [inline corpus/integration_test.go]: Why do we need this?

File: corpus/integration_test.go [hunk 7]
```diff
@@ -162,18 +190,52 @@ func TestIntegrationSuite(t *testing.T) {
...
-	var panicValue interface{}
+func runTest(balFile string) (stdout, stderr string) {
+	var stderrBuilder strings.Builder
 
 	func() {
 		defer func() {
 			if r := recover(); r != nil {
-				panicOccurred = true
-				panicValue = r
+				fmt.Fprintf(&stderrBuilder, "panic: %v\n", r)
```
Comment (heshanpadmasiri) [inline corpus/integration_test.go]: I would expect panic prefix to come from the runtime instead of having to add it here

File: semantics/corpus_semantic_analysis_test.go [hunk 8]
```diff
@@ -146,7 +146,15 @@ func (v *semanticAnalysisValidator) VisitTypeData(typeData *model.TypeData) ast.
 }
 
 var semanticAnalysisErrorSkipList = []string{
-	// No skipped tests
+	// reachability analysis
```
Comment (heshanpadmasiri) [inline semantics/corpus_semantic_analysis_test.go]: Why?

File: semantics/corpus_semantic_analysis_test.go [hunk 9]
```diff
@@ -169,37 +177,23 @@ func testSemanticAnalysisError(t *testing.T, testCase test_util.TestCase) {
...
-			return
-		}
+	defer func() {
+		recover()
 
-		// Verify the panic is a syntax or semantic error (not some other panic)
-		panicStr := fmt.Sprintf("%v", panicValue)
-		if !strings.Contains(panicStr, "Semantic error:") && !strings.Contains(panicStr, "Syntax error:") {
-			t.Errorf("Expected syntax or semantic error for %s, but got different panic: %v", testCase.InputPath, panicValue)
+		if !cx.HasDiagnostics() {
```
Comment (heshanpadmasiri) [inline semantics/corpus_semantic_analysis_test.go]: I am not convinced this is a good idea. I think HasDiagnostics should be true even if we have internal errors or unimplemented errors so that we don't go to the next stages.

File: semantics/corpus_semantic_analysis_test.go [hunk 10]
```diff
@@ -169,37 +177,23 @@ func testSemanticAnalysisError(t *testing.T, testCase test_util.TestCase) {
...
+			t.Errorf("Expected semantic errors for %s, but no errors were recorded", testCase.InputPath)
```
Comment (heshanpadmasiri) [inline semantics/corpus_semantic_analysis_test.go:186]: Why?

File: semantics/semantic_analyzer.go [hunk 11]
```diff
@@ -459,15 +459,38 @@ func analyzeExpression[A analyzer](a A, expr ast.BLangExpression, expectedType s
 	switch expr := expr.(type) {
 	// Literals - just validate
 	case *ast.BLangLiteral:
-		validateResolvedType(a, expr, expectedType)
-
+		if expectedType == nil {
```
Comment (heshanpadmasiri) [inline semantics/semantic_analyzer.go]: We should be able to handle early return properly duplicating the logic in every place.

**Comment by warunalakshitha** [comment]
Shall we address the coderabbit comments and sync with latest changes from main branch.Also resolve any fixed(addressed) comments too.

**Comment by snelusha** [comment]
> Shall we address the coderabbit comments and sync with latest changes from main branch.Also resolve any fixed(addressed) comments too.

Working on this

File: ast/node_builder.go [hunk 12]
```diff
@@ -581,19 +581,105 @@ func (n *NodeBuilder) TransformSyntaxNode(node tree.Node) BLangNode {
 	}
 }
 
+func getFileName(node tree.Node) string {
+	st := node.SyntaxTree()
+	if st != nil {
+		return st.FilePath()
+	}
+	return ""
```
Comment (warunalakshitha) [inline ast/node_builder.go]: Should we panic here?

File: ast/node_builder.go [hunk 13]
```diff
@@ -581,19 +581,105 @@ func (n *NodeBuilder) TransformSyntaxNode(node tree.Node) BLangNode {
...
+		textRange.StartOffset,
+		textRange.Length,
+	)
 }
 
 func getPositionRange(startNode tree.Node, endNode tree.Node) Location {
-	// FIXME:
-	return nil
+	if startNode == nil || endNode == nil {
+		return nil
```
Comment (warunalakshitha) [inline ast/node_builder.go]: can this be happen. we can remove and see

File: ast/node_builder.go [hunk 14]
```diff
@@ -581,19 +581,105 @@ func (n *NodeBuilder) TransformSyntaxNode(node tree.Node) BLangNode {
...
+		startNodeTextRange.StartOffset,
+		length,
+	)
 }
 
 func getPositionWithoutMetadata(node tree.Node) Location {
-	// FIXME:
-	return nil
+	if node == nil {
+		return nil
```
Comment (warunalakshitha) [inline ast/node_builder.go]: I think node will never be nil

File: ast/node_builder.go [hunk 15]
```diff
@@ -581,19 +581,105 @@ func (n *NodeBuilder) TransformSyntaxNode(node tree.Node) BLangNode {
...
+
+	if firstChild != nil && firstChild.Kind() == common.METADATA && secondChild != nil {
+		secondLineRange := secondChild.LineRange()
+		startLine = secondLineRange.StartLine.Line
+		startColumn = secondLineRange.StartLine.Column
+		secondTextRange := secondChild.TextRange()
+		startOffset = secondTextRange.StartOffset
+		firstTextRange := firstChild.TextRange()
+		nodeTextRange := node.TextRange()
+		length = nodeTextRange.Length - firstTextRange.Length
```
Comment (warunalakshitha) [inline ast/node_builder.go:652]: Why this lines were not covered

File: context/context.go [hunk 16]
```diff
@@ -81,66 +64,60 @@ func (this *CompilerContext) SetSymbolType(symbol model.SymbolRef, ty semtypes.S
...
 }
 
 func (this *CompilerContext) Unimplemented(message string, pos diagnostics.Location) {
-	if pos != nil {
-		panic(fmt.Sprintf("Unimplemented: %s at %s", message, pos))
-	}
-	panic(fmt.Sprintf("Unimplemented: %s", message))
+	code := "UNIMPLEMENTED_ERROR"
+	diagnosticInfo := diagnostics.NewDiagnosticInfo(&code, message, diagnostics.Internal)
+	diagnostic := diagnostics.CreateDiagnostic(diagnosticInfo, pos)
```
Comment (warunalakshitha) [inline context/context.go]: Shall we create the diagnosticInfo inside CreateDiagnostic?

File: semantics/semantic_analyzer.go [hunk 17]
```diff
@@ -192,68 +193,116 @@ func (la *loopAnalyzer) tyCtx() semtypes.Context {
 	return la.parent.tyCtx()
 }
 
-func (sa *SemanticAnalyzer) unimplementedErr(message string) {
-	sa.compilerCtx.Unimplemented(message, nil)
+func (sa *SemanticAnalyzer) unimplementedErr(message string, loc diagnostics.Location) {
+	if loc == nil {
+		loc = sa.loc()
```
Comment (warunalakshitha) [inline semantics/semantic_analyzer.go]: seems loc never nil

File: parser/tree/syntax_tree.go [hunk 18]
```diff
@@ -17,25 +17,31 @@
...
 type SyntaxTree struct {
 	RootNode     Node
 	filePath     string
-	textDocument TextDocument
+	textDocument text.TextDocument
 	// lineRange    LineRange
 }
 
-func NewSyntaxTreeFromNodeTextDocumentStringBool(rootNode Node, textDocument TextDocument, filePath string, clone bool) SyntaxTree {
+func NewSyntaxTreeFromNodeTextDocumentStringBool(rootNode Node, textDocument text.TextDocument, filePath string, clone bool) SyntaxTree {
```
Comment (warunalakshitha) [inline parser/tree/syntax_tree.go]: Can we rename to NewSyntaxTreeFromNodeTextDocument

File: parser/tree/node.go [hunk 19]
```diff
@@ -284,13 +287,38 @@ func (n *NodeBase) SyntaxTree() *SyntaxTree {
 }
 
 func (n *NodeBase) LineRange() LineRange {
-	if n.lineRange.startLine.line != 0 || n.lineRange.endLine.line != 0 {
+	if n.lineRange.StartLine.Line != 0 || n.lineRange.EndLine.Line != 0 {
+		return n.lineRange
+	}
+
+	syntaxTree := n.SyntaxTree()
+	if syntaxTree == nil {
```
Comment (warunalakshitha) [inline parser/tree/node.go]: Can this be nil

File: context/env.go [hunk 20]
```diff
@@ -0,0 +1,148 @@
...
+	if pos != nil {
+		panic(fmt.Sprintf("Semantic error: %s at %s", message, pos))
+	}
+	panic(fmt.Sprintf("Semantic error: %s", message))
+}
+
+// TODO: implement these properly
+func (this *CompilerEnvironment) SyntaxError(message string, pos diagnostics.Location) {
+	if pos != nil {
+		panic(fmt.Sprintf("Syntax error: %s at %s", message, pos))
```
Comment (warunalakshitha) [inline context/env.go]: why these not covered by tests?

File: ast/node_builder.go (hunk 15 above)
Comment (snelusha) [reply ast/node_builder.go:652]: Because we currently don't have any test that include metadata

File: context/context.go [hunk 21]
```diff
@@ -81,66 +64,56 @@ func (this *CompilerContext) SetSymbolType(symbol model.SymbolRef, ty semtypes.S
...
 
-func (this *CompilerContext) InternalError(message string, pos diagnostics.Location) {
-	if pos != nil {
-		panic(fmt.Sprintf("Internal error: %s at %s", message, pos))
-	}
-	panic(fmt.Sprintf("Internal error: %s", message))
+func (this *CompilerContext) SemanticError(message string, pos diagnostics.Location) {
+	code := "SEMANTIC_ERROR"
+	diagnostic := diagnostics.CreateDiagnostic(diagnostics.NewDiagnosticInfo(&code, message, diagnostics.Error), pos)
+	this.diagnostics = append(this.diagnostics, diagnostic)
```
Comment (heshanpadmasiri) [inline context/context.go]: As far as I can see all these are esstentially same except for code. If similarity is not accidentaly extract the common logic out

File: context/env.go [hunk 22]
```diff
@@ -0,0 +1,117 @@
...
+package context
+
+import (
+	"strconv"
+
+	"ballerina-lang-go/model"
+	"ballerina-lang-go/semtypes"
+)
+
+// TODO: consider moving type resolution env in to this
```
Comment (heshanpadmasiri) [inline context/env.go]: This is fixed right?

File: semantics/corpus_semantic_analysis_test.go [hunk 23]
```diff
@@ -169,37 +170,26 @@ func testSemanticAnalysisError(t *testing.T, testCase test_util.TestCase) {
...
 		if r := recover(); r != nil {
-			didPanic = true
-			panicValue = r
+			t.Errorf("Semantic analysis panicked for %s: %v", testCase.InputPath, r)
 		}
 
-		// After recovery, verify that a syntax or semantic error occurred
-		if !didPanic {
-			t.Errorf("Expected syntax or semantic error for %s, but analysis completed without error", testCase.InputPath)
+		if !cx.HasDiagnostics() {
```
Comment (heshanpadmasiri) [inline semantics/corpus_semantic_analysis_test.go]: It must be a syntax error or semantic error I think this also allows unimplemented errors

File: semantics/type_resolver.go [hunk 24]
```diff
@@ -224,9 +231,13 @@ func (t *TypeResolver) resolveTypeDefinition(defn *ast.BLangTypeDefinition, dept
 	}
 	if depth == defn.CycleDepth {
 		t.ctx.SemanticError(fmt.Sprintf("invalid cycle detected for type definition %s", defn.Name.GetValue()), defn.GetPosition())
+		return nil
 	}
 	defn.CycleDepth = depth
```
Comment (heshanpadmasiri) [inline semantics/type_resolver.go]: I think I am okay we analyze functions returning bool (current design), but I think then it needs to be consistent so let's return a tuple here

File: ast/node_builder.go [hunk 25]
```diff
@@ -580,19 +580,96 @@ func (n *NodeBuilder) TransformSyntaxNode(node tree.Node) BLangNode {
...
+func getFileName(node tree.Node) string {
+	st := node.SyntaxTree()
+	return st.FilePath()
+}
+
 func getPosition(node tree.Node) Location {
-	// FIXME:
-	return nil
+	if node == nil {
+		panic("node is nil")
```
Comment (warunalakshitha) [inline ast/node_builder.go]: Since it is not covered we can remove

File: semantics/semantic_analyzer.go [hunk 26]
```diff
@@ -1044,53 +1097,59 @@ type assignmentNode interface {
...
+	return analyzeExpression(a, ifStmt.Expr, &semtypes.BOOLEAN)
 }
 
-func analyzeWhile[A analyzer](a A, whileStmt *ast.BLangWhile) {
-	analyzeExpression(a, whileStmt.Expr, &semtypes.BOOLEAN)
+func analyzeWhile[A analyzer](a A, whileStmt *ast.BLangWhile) bool {
+	return analyzeExpression(a, whileStmt.Expr, &semtypes.BOOLEAN)
 }
 
 func validateForeach[A analyzer](a A, foreachStmt *ast.BLangForeach) {
```
Comment (heshanpadmasiri) [inline semantics/semantic_analyzer.go]: If this fails you should go to next statement as well

File: semantics/type_resolver.go [hunk 27]
```diff
@@ -85,65 +91,97 @@ func (t *TypeResolver) ResolveTypes(ctx *context.CompilerContext, pkg *ast.BLang
...
 	paramListDefn := semtypes.NewListDefinition()
 	paramListTy := paramListDefn.DefineListTypeWrapped(t.ctx.GetTypeEnv(), paramTypes, len(paramTypes), restTy, semtypes.CellMutability_CELL_MUT_NONE)
 	var returnTy semtypes.SemType
 	if retTd := fn.GetReturnTypeDescriptor(); retTd != nil {
-		returnTy = t.resolveBType(retTd.(ast.BType), 0)
+		var ok bool
+		returnTy, ok = t.resolveBType(retTd.(ast.BType), 0)
+		if !ok {
+			return nil, false
+		}
```
Comment (heshanpadmasiri) [inline semantics/type_resolver.go:186]:
```suggestion
		returnTy, ok := t.resolveBType(retTd.(ast.BType), 0)
		if !ok {
			return nil, false
		}
```

File: semantics/type_resolver.go [hunk 28]
```diff
@@ -268,36 +315,46 @@ func (t *TypeResolver) resolveLiteral(n *ast.BLangLiteral) {
 		var r *big.Rat
 		switch v := n.GetValue().(type) {
 		case string:
-			r = t.parseDecimalValue(stripFloatingPointTypeSuffix(v), n.GetPosition())
+			parsed, ok := t.parseDecimalValue(stripFloatingPointTypeSuffix(v), n.GetPosition())
+			if !ok {
+				return false
+			}
+			r = parsed
```
Comment (heshanpadmasiri) [inline semantics/type_resolver.go]: Why we need temperary variable parsed here?

File: semantics/type_resolver.go [hunk 29]
```diff
@@ -268,36 +315,46 @@ func (t *TypeResolver) resolveLiteral(n *ast.BLangLiteral) {
...
 	case model.TypeTags_FLOAT:
 		var f float64
 		switch v := n.GetValue().(type) {
 		case string:
-			f = t.parseFloatValue(stripFloatingPointTypeSuffix(v), n.GetPosition())
+			parsed, ok := t.parseFloatValue(v, n.GetPosition())
+			if !ok {
+				return false
+			}
+			f = parsed
```
Comment (heshanpadmasiri) [inline semantics/type_resolver.go]: ditto

File: semantics/type_resolver.go [hunk 30]
```diff
@@ -310,82 +367,105 @@ func stripFloatingPointTypeSuffix(s string) string {
...
+		if !ok {
+			return false
+		}
 	case model.NodeKind_HEX_FLOATING_POINT_LITERAL:
-		ty = t.resolveHexFloatingPointLiteral(n, typeTag)
+		var ok bool
+		ty, ok = t.resolveHexFloatingPointLiteral(n, typeTag)
+		if !ok {
+			return false
+		}
```
Comment (heshanpadmasiri) [inline semantics/type_resolver.go]: No need for ok here as well

File: semantics/type_resolver.go [hunk 31]
```diff
@@ -449,19 +539,30 @@ func (t *TypeResolver) resolveExpression(expr ast.BLangExpression) semtypes.SemT
...
 		setExpectedType(e, ty)
-		return ty
+		return ty, true
 	case *ast.BLangTypeConversionExpr:
-		return t.resolveTypeConversionExpr(e)
+		ty, ok := t.resolveTypeConversionExpr(e)
+		if !ok {
+			return nil, false
+		}
+		return ty, true
```
Comment (heshanpadmasiri) [inline semantics/type_resolver.go]: Why can't we just return directly here?

File: semantics/type_resolver.go [hunk 32]
```diff
@@ -449,19 +539,30 @@ func (t *TypeResolver) resolveExpression(expr ast.BLangExpression) semtypes.SemT
...
 	case *ast.BLangTypeTestExpr:
-		return t.resolveTypeTestExpr(e)
+		ty, ok := t.resolveTypeTestExpr(e)
```
Comment (heshanpadmasiri) [inline semantics/type_resolver.go]: ditto

File: semantics/type_resolver.go [hunk 33]
```diff
@@ -1074,95 +1233,121 @@ func (tr *TypeResolver) resolveBTypeInner(btype ast.BType, depth int) semtypes.S
...
+			return tr.ctx.SymbolType(symbol), true
 		}
 		defn, ok := tr.typeDefns[symbol]
 		if !ok {
 			// This should have been detected by the symbol resolver
 			tr.ctx.InternalError("type definition not found", nil)
-			return nil
+			return nil, false
+		}
+		semTy, ok := tr.resolveTypeDefinition(defn, depth)
```
Comment (heshanpadmasiri) [inline semantics/type_resolver.go]: just return

File: semantics/type_resolver.go [hunk 34]
```diff
@@ -1172,11 +1357,17 @@ func (t *TypeResolver) resolveConstant(constant *ast.BLangConstant) {
 	exprType := constant.Expr.(ast.BLangExpression).GetDeterminedType()
 	var expectedType semtypes.SemType
 	if typeNode := constant.TypeNode(); typeNode != nil {
-		expectedType = t.resolveBType(typeNode, 0)
+		var ok bool
+		expectedType, ok = t.resolveBType(typeNode, 0)
+		if !ok {
+			return false
+		}
```
Comment (heshanpadmasiri) [inline semantics/type_resolver.go:1545]:
```suggestion
		expectedType, ok := t.resolveBType(typeNode, 0)
		if !ok {
			return false
		}
```

**Review by heshanpadmasiri — CHANGES_REQUESTED** [review]

**Review by heshanpadmasiri — COMMENTED** [review]
mostly nits; generally LGTM

File: semantics/corpus_cfg_test.go [hunk 35]
```diff
@@ -67,7 +68,8 @@ func testCFGGeneration(t *testing.T, testPair test_util.TestCase) {
 	defer close(debugCtx.Channel)
 
 	// Create compiler context
-	cx := context.NewCompilerContext(semtypes.CreateTypeEnv())
+	env := context.NewCompilerEnvironment(semtypes.CreateTypeEnv())
+	cx := context.NewCompilerContext(env)
```
Comment (azinneera) [inline semantics/corpus_cfg_test.go:72]: Do we need this? The CompilerContext is created in moduleContext

File: semantics/corpus_semantic_analysis_test.go [hunk 36]
```diff
@@ -53,7 +53,8 @@ func testSemanticAnalysis(t *testing.T, testCase test_util.TestCase) {
 	debugCtx := debugcommon.DebugContext{
 		Channel: make(chan string),
 	}
-	cx := context.NewCompilerContext(semtypes.CreateTypeEnv())
+	env := context.NewCompilerEnvironment(semtypes.CreateTypeEnv())
+	cx := context.NewCompilerContext(env)
```
Comment (azinneera) [inline semantics/corpus_semantic_analysis_test.go:57]: Refer to the previous comment

File: semantics/type_resolver.go [hunk 37]
```diff
@@ -85,65 +91,97 @@ func (t *TypeResolver) ResolveTypes(ctx *context.CompilerContext, pkg *ast.BLang
...
+			}
 		}
 	case *ast.BLangBreak, *ast.BLangContinue:
 		// No expressions to resolve
 	default:
 		t.ctx.InternalError(fmt.Sprintf("unexpected statement type: %T", s), s.GetPosition())
+		return false
 	}
+	return true
 }
```
Comment (warunalakshitha) [inline semantics/type_resolver.go:165]:
```suggestion
func (t *TypeResolver) resolveStatement(stmt ast.BLangStatement) bool {
	switch s := stmt.(type) {

	case *ast.BLangSimpleVariableDef:
		variable := s.GetVariable().(*ast.BLangSimpleVariable)
		if !t.resolveExpr(variable.Expr.(ast.BLangExpression)) {
			return false
		}

	case *ast.BLangAssignment:
		return t.resolveExpr(s.GetVariable().(ast.BLangExpression)) &&
			t.resolveExpr(s.GetExpression().(ast.BLangExpression))

	case *ast.BLangCompoundAssignment:
		return t.resolveExpr(s.GetVariable().(ast.BLangExpression)) &&
			t.resolveExpr(s.GetExpression().(ast.BLangExpression))

	case *ast.BLangExpressionStmt:
		return t.resolveExpr(s.Expr)

	case *ast.BLangIf:
		return t.resolveExpr(s.Expr) &&
			t.resolveBlockStatements(s.Body.Stmts) &&
			(s.ElseStmt == nil || t.resolveStatement(s.ElseStmt))

	case *ast.BLangWhile:
		return t.resolveExpr(s.Expr) &&
			t.resolveBlockStatements(s.Body.Stmts)

	case *ast.BLangReturn:
		return t.resolveExpr(s.Expr)

	case *ast.BLangBreak, *ast.BLangContinue:
		return true

	default:
		t.ctx.InternalError(
			fmt.Sprintf("unexpected statement type: %T", s),
			s.GetPosition(),
		)
		return false
	}
}
```

File: semantics/type_resolver.go [hunk 38]
```diff
@@ -310,82 +363,105 @@ func stripFloatingPointTypeSuffix(s string) string {
...
+	if ty == nil {
+		return false
 	}
 
 	setExpectedType(n, ty)
 
 	// Update symbol type if this numeric literal has a symbol
 	updateSymbolType(t.ctx, n, ty)
+	return true
 }
```
Comment (warunalakshitha) [inline semantics/type_resolver.go:424]:
```suggestion
func (t *TypeResolver) resolveNumericLiteral(n *ast.BLangNumericLiteral) bool {
	bType := n.GetValueType()
	typeTag := bType.BTypeGetTag()

	var (
		ty semtypes.SemType
		ok bool
	)

	switch n.Kind {
	case model.NodeKind_INTEGER_LITERAL:
		ty, ok = t.resolveIntegerLiteral(n, typeTag)

	case model.NodeKind_DECIMAL_FLOATING_POINT_LITERAL:
		ty, ok = t.resolveDecimalFloatingPointLiteral(n, typeTag)

	case model.NodeKind_HEX_FLOATING_POINT_LITERAL:
		ty, ok = t.resolveHexFloatingPointLiteral(n, typeTag)

	default:
		t.ctx.InternalError(
			fmt.Sprintf("unexpected numeric literal kind: %v", n.Kind),
			n.GetPosition(),
		)
		return false
	}

	if !ok || ty == nil {
		return false
	}

	setExpectedType(n, ty)
	updateSymbolType(t.ctx, n, ty)

	return true
}
```

File: semantics/type_resolver.go [hunk 39]
```diff
@@ -310,82 +363,105 @@ func stripFloatingPointTypeSuffix(s string) string {
...
+		}
 		n.SetValue(r)
-		return semtypes.DecimalConst(*r)
+		return semtypes.DecimalConst(*r), true
 	default:
 		t.ctx.InternalError(fmt.Sprintf("unexpected type tag %v for decimal floating point literal", typeTag), n.GetPosition())
-		return nil
+		return nil, false
 	}
 }
```
Comment (warunalakshitha) [inline semantics/type_resolver.go:460]:
```suggestion
func (t *TypeResolver) resolveDecimalFloatingPointLiteral(
	n *ast.BLangNumericLiteral,
	typeTag model.TypeTags,
) (semtypes.SemType, bool) {

	strValue := stripFloatingPointTypeSuffix(n.GetValue().(string))

	switch typeTag {

	case model.TypeTags_FLOAT:
		val, ok := t.parseFloatValue(strValue, n.GetPosition())
		if !ok {
			return nil, false
		}
		n.SetValue(val)
		return semtypes.FloatConst(val.(float64)), true

	case model.TypeTags_DECIMAL:
		val, ok := t.parseDecimalValue(strValue, n.GetPosition())
		if !ok {
			return nil, false
		}
		n.SetValue(val)
		return semtypes.DecimalConst(*(val.(*Decimal))), true
	}

	// Unexpected type tag
	t.ctx.InternalError(
		fmt.Sprintf("unexpected type tag %v for decimal floating point literal", typeTag),
		n.GetPosition(),
	)
	return nil, false
}
```

File: semantics/corpus_cfg_test.go (hunk 35 above)
Comment (snelusha) [reply semantics/corpus_cfg_test.go:72]: Here we don't use project api.

File: semantics/type_resolver.go (hunk 39 above)
Comment (snelusha) [reply semantics/type_resolver.go:460]: invalid operation: val (variable of type float64) is not an interface.
invalid operation: val (variable of type *big.Rat) is not an interface.

File: semantics/type_resolver.go (hunk 37 above)
Comment (snelusha) [reply semantics/type_resolver.go:165]: `t.resolveExpression()` function returns `(semtypes.SemType, bool)`

**Review by warunalakshitha — APPROVED** [review]
